name: yexder_mobile_client
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/application-icon.png"

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  http: ^1.2.1
  google_fonts: ^6.2.1
  flutter_secure_storage: ^5.0.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.1.8
  mobx_codegen: ^2.0.5+2
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/